apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    name: nginx
    version: v1
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
