apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    tier: frontend
spec:
  replicas: 3  # no of pods
  minReadySeconds: 1 # seconds the pod should be ready once container is up and running
  progressDeadlineSeconds: 60 # seconds to wait before reporting stalled deployments
  revisionHistoryLimit: 5 # no of repicas that can be rolled back
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # max surge pod that can be available during rolllout
      maxUnavailable: 1 # min working pod before rollout complete
      
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
