apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: busy-echo
spec:
    schedule: "*/1 * * * * "
    concurrencyPolicy: Allow
    jobTemplate:
       spec:
           template:
               spec:
                   restartPolicy: OnFailure
                   
                   containers:
                       - name: echo-hello
                         image: busybox
                         args: 
                         - /bin/sh
                         - -c 
                         - date; echo Hello from the Kubernetes cluster