apiVersion: batch/v1
kind: Job
metadata:
    name: pi
spec:
    completions: 4
    parallelism: 2
    template:
        spec:
            containers:
                - name: pi
                  image: perl
                  command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
            restartPolicy: Never
    ttlSecondsAfterFinished: 100 #Job will be eligible to be automatically deleted, 100 seconds after it finishes.
    backoffLimit: 4 # try 4 times before backing off in case of errors+
    activeDeadlineSeconds: 100 # setting a deadline to the active job- if job is not completed within this time line the job is teminated with failed state

