apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-configmap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-configmap
  template:
    metadata:
      labels:
        app: node-configmap
    spec:
      # Define volume that will contain ConfigMap data
      volumes:
        - name: app-config-vol
          configMap:
            name: app-settings 
      # Define volume that will contain secret data
        - name: app-secret-vol
          secret:
              secretName: test-secret-file 
      containers:
      - name: node-configmap
        image: node-configmap:1.0
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        volumeMounts:
          - name: app-config-vol
            mountPath: /etc/config
          - name: app-secret-vol
            mountPath: /etc/secret
              # Map env variable data to a ConfigMap property
        env:
         - name: Owner
           valueFrom: 
             configMapKeyRef:
               name: app-settings
               key: owner
         - name: husband
           valueFrom:
               secretKeyRef:
                 name: sensitive-data
                 key: me
         - name: wife
           valueFrom:
               secretKeyRef:
                 name: sensitive-data
                 key: wife
        # Load all ConfigMap keys/values into environment variables (simplified way if you need them all vs. only a few as with "env" above)
        envFrom:
         - configMapRef:
             name: app-settings
      
---

apiVersion: v1
kind: Service
metadata:
  name: node-configmap-svc
spec:
  selector:
    app: node-configmap
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 9000

