apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo
  labels:
    example: canary
spec:
  replicas: 2
  minReadySeconds: 1
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        example: canary
        app: k8s-demo
    spec:
      containers:
      - name: k8s-demo
        image: srini/k8s-demo:1.0
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 5
            timeoutSeconds: 2
            failureThreshold: 1
            periodSeconds: 30
            
        ports:
        - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: stable-service
  labels:
    app: stable-app
spec:
  type: LoadBalancer
  selector:
    example: canary
    # app: stable-app
  ports:
  - port: 8080
    targetPort: 8090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-update-demo
  labels:
    example: canary
spec:
  replicas: 1
  minReadySeconds: 1
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        example: canary
        app: k8s-demo
    spec:
      containers:
      - name: k8s-demo
        image: srini/k8s-demo:2.0
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 5
            timeoutSeconds: 2
            failureThreshold: 1
            periodSeconds: 30
            
        ports:
        - containerPort: 8090